version: "3.8"

services:
  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["yarn", "start"]
    expose:
      - "3001"
